# Generated by Django 6.0 on 2025-12-16 13:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default=39.9, max_digits=10, verbose_name='价格')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('difficulty_level', models.CharField(choices=[('入门级', '入门级'), ('进阶级', '进阶级'), ('专家级', '专家级')], default='入门级', max_length=20, verbose_name='难度级别')),
                ('target_audience', models.CharField(choices=[('通用', '通用'), ('男生偏好', '男生偏好'), ('女生偏好', '女生偏好')], default='通用', max_length=20, verbose_name='目标读者')),
                ('score', models.DecimalField(decimal_places=1, default=8.5, max_digits=3, verbose_name='评分')),
                ('book_status', models.CharField(choices=[('已完结', '已完结'), ('连载中', '连载中')], default='已完结', max_length=20, verbose_name='图书状态')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='App1.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='手机号')),
                ('reading_hobbies', models.TextField(blank=True, verbose_name='阅读兴趣')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', '想读'), ('reading', '在读中'), ('completed', '已读完')], default='planned', max_length=20, verbose_name='阅读状态')),
                ('progress', models.IntegerField(default=0, verbose_name='阅读进度(%)')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='个人评分')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_read', models.DateTimeField(auto_now=True, verbose_name='最后阅读时间')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, verbose_name='读书笔记')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.book', verbose_name='书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户书架',
                'verbose_name_plural': '用户书架',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
